title = "Acura Integra Type R"
description = "Acura Integra Type R sports car."
date = "2022-12-20"
sketchfab_url = "https://sketchfab.com/3d-models/acura-integra-type-r-457a982d3b8946f89cb545ed7e21390c"
instagram_url = ""
tags = ["vehicle", "car", "acura", "sports-car"]
