title = "Battleship Board"
description = "Battleship game board model."
date = "2023-06-05"
sketchfab_url = "https://sketchfab.com/3d-models/tablero-de-battleship-1c8864491cce4c0f89830ce68b4e994f"
instagram_url = ""
tags = ["game", "board-game", "battleship"]
