title = "BMW M3"
description = "BMW M3 sports car model."
date = "2023-03-10"
sketchfab_url = "https://sketchfab.com/3d-models/bmw-m3-1c9d4cfc2af14e658dce81298f324e2f"
instagram_url = ""
tags = ["vehicle", "car", "bmw", "sports-car"]
