title = "Chess Set"
description = "Complete chess set with board and pieces."
date = "2022-11-01"
sketchfab_url = "https://sketchfab.com/3d-models/ajedrez-chess-38a83ee10d874bc6825c858760f0d3ae"
instagram_url = ""
tags = ["game", "chess", "board-game"]
