title = "Classroom"
description = "School classroom environment."
date = "2023-05-15"
sketchfab_url = "https://sketchfab.com/3d-models/aula-de-clase-c928c4d3de9446b789157b3e0b19846f"
instagram_url = ""
tags = ["environment", "classroom", "interior"]
