title = "Dodge Charger 70s"
description = "Classic 1970s Dodge Charger muscle car."
date = "2023-09-15"
sketchfab_url = "https://sketchfab.com/3d-models/dodge-charger-70s-fa2a7430fd094b79bdc45f4d29aac1ed"
instagram_url = ""
tags = ["vehicle", "car", "classic", "muscle-car"]
