title = "Fiat 850"
description = "Classic Fiat 850 car model."
date = "2023-02-05"
sketchfab_url = "https://sketchfab.com/3d-models/fiat-850-5f805832c97840d2a580bad72026b48f"
instagram_url = ""
tags = ["vehicle", "car", "fiat", "classic"]
