title = "Granero"
description = "Barn structure model."
date = "2023-10-20"
sketchfab_url = "https://sketchfab.com/3d-models/granero-2de5076e091941aca91d598e41f292b3"
instagram_url = ""
tags = ["architecture", "barn", "building"]
