title = "Lamps"
description = "Collection of lamp models."
date = "2023-01-25"
sketchfab_url = "https://sketchfab.com/3d-models/lamps-c082bd6aaeca4e16991324f127b4e6c8"
instagram_url = ""
tags = ["prop", "lamp", "lighting"]
