title = "Low Poly P250"
description = "Low poly P250 pistol model."
date = "2023-04-20"
sketchfab_url = "https://sketchfab.com/3d-models/low-poly-p250-87665f4bd1d94bf38a61a7d47718cb58"
instagram_url = ""
tags = ["weapon", "low-poly", "pistol", "game-asset"]
