title = "Low Poly P2000"
description = "Low poly P2000 pistol model."
date = "2023-04-15"
sketchfab_url = "https://sketchfab.com/3d-models/low-poly-p2000-a7d44877d6cf41e782304e62fd59a9d2"
instagram_url = ""
tags = ["weapon", "low-poly", "pistol", "game-asset"]
