title = "Messy Room"
description = "Cluttered bedroom environment."
date = "2023-02-20"
sketchfab_url = "https://sketchfab.com/3d-models/messy-room-e06edeeebe0a42f0b9c10865cfd945ee"
instagram_url = ""
tags = ["environment", "interior", "bedroom"]
