title = "Minecraft Crab"
description = "New Minecraft mob - crab creature."
date = "2023-08-10"
sketchfab_url = "https://sketchfab.com/3d-models/cangrejo-de-minecraft-nuevo-mob-de-minecraft-5bb6b116495441c98b44037e3dcf585e"
instagram_url = ""
tags = ["minecraft", "mob", "creature", "game-asset"]
