title = "Shotgun"
description = "Shotgun weapon model."
date = "2023-01-10"
sketchfab_url = "https://sketchfab.com/3d-models/shotgum-d5b799ee85854b0f933062ce4053c6c1"
instagram_url = ""
tags = ["weapon", "shotgun"]
