title = "Small Warship"
description = "Small military warship model."
date = "2022-10-15"
sketchfab_url = "https://sketchfab.com/3d-models/buque-de-guerra-pequeno-3d56c78931d54116988a988772b62eb9"
instagram_url = ""
tags = ["vehicle", "ship", "military", "warship"]
