title = "Stunt Track - Rush 2: Extreme Racing USA"
description = "Racing track from Rush 2: Extreme Racing USA game."
date = "2022-11-15"
sketchfab_url = "https://sketchfab.com/3d-models/stunt-track-rush-2-extreme-racing-usa-5ce76605e8e64eae8075340349b6267e"
instagram_url = ""
tags = ["environment", "racing", "track", "game-asset"]
