title = "Winchester"
description = "Winchester rifle weapon model."
date = "2023-07-10"
sketchfab_url = "https://sketchfab.com/3d-models/winchester-fee3471aa828408ab253f5e31c3be643"
instagram_url = ""
tags = ["weapon", "rifle", "winchester"]
