title = "WWII Weapons Mini Pack"
description = "Collection of low poly WWII era weapons."
date = "2023-03-25"
sketchfab_url = "https://sketchfab.com/3d-models/wwii-weapons-mini-pack-low-poly-e4df5f5efed345e5ac721fac359fb969"
instagram_url = ""
tags = ["weapon", "low-poly", "wwii", "pack"]
